## 1. 넘파이 ndarray 개요

In [9]:
import numpy as np

array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)

array2 = np.array([[1,2,3],
                   [4,5,6]])
print(type(array2))
print(array2.shape)


array3 = np.array([[1,2,3]])
print(type(array3))
print(array3.shape)

print('array1:{0}차원, array2:{1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim,array3.ndim))


<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)
array1:1차원, array2:2차원, array3: 2차원


## 2. ndarray의 데이터 타입

In [17]:
# 연산 특성상 같은 데이터 타입만 가능하다. 
# 데이터 타입이 섞여있을 시 데이터 터입이 더 큰 데이터 타입으로 변환된다. 
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [21]:
# astype() : 데이터 타입 변경 
# 메모리 절약을 위해 float -> int로 데이터 타입을 변경할 때가 있다. 

array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1 = np.array([1.1,2.2,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2,array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## 3. ndarray를 편리하게 생성하기 : arange, zeros, ones

- 테스트용 데이터를 만들거나 대규모 데이터를 일괄적으로 초기화할 경우에 사용된다.
- 연속값이나 0,1로 초기화히여 ndarray를 쉽게 생성힌다.

In [23]:
# 1. arange(n) : 0 ~ n-1까지 순차적으로 값 부여 
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [29]:
# 2. zeros: 0으로 값 채움 
zero_array = np.zeros((3,2), dtype= "int32")
print(zero_array)
print(zero_array.dtype, zero_array.shape)
# 3. ones: 1로 값 채움
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

#dtype을 정하지 않으면 float형태로 반환

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## 4. ndarray 차원 크기 변경 : reshape()

In [34]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3  = array1.reshape(5,2)
print('array3:\n', array3)


array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [35]:
# -1을 인자로 두면 알아서 차원을 맞추어준다. 
array4 = array1.reshape(-1,5)
print('array4:\n', array4)

array5 = array1.reshape(5,-1)
print('array5:\n', array5)


array4:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array5:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [47]:
# reshape(-1,1) : 원본 ndarray를 여러 행과 단 1개의 열을 지닌 2차원 형태로 변환시킨다. 

array3d = array1.reshape(2,2,2)
print('array3d:\n', array3d.tolist())

#3차원 -> 2차원
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape', array5.shape)

#1차원 -> 2차원
array1 = np.arange(8)
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape (8, 1)


## 5. ndarray의 데이터 셋 선택하기 : 인덱싱

In [50]:
array1 = np.arange(start=1, stop= 10)
print("array1:", array1)

value = array1[2]
print(value, value.dtype)

array1: [1 2 3 4 5 6 7 8 9]
3 int64


In [51]:
array1[0] = 10
array1[-1] = 0
print(array1)

[10  2  3  4  5  6  7  8  0]


In [61]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print(array2d[0,0])
print(array2d[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[4 5 6]


In [66]:
# 슬라이싱 : ":" 로 구간 정한다. 
print(array1)
a = array1[1:3]
print(a, type(a))

[10  2  3  4  5  6  7  8  0]
[2 3] <class 'numpy.ndarray'>


In [72]:
# 팬시 인덱싱: 인덱스 집합을 지정하는 인덱싱 
print("array2d\n", array2d)

array3 = array2d[[0,1],2]
print("array3:",array3.tolist())

array4 = array2d[[0,1],0:2]
print("array4:",array4.tolist())

array5 = array2d[[0,1]]
print("array5:",array5.tolist())



array2d
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array3: [3, 6]
array4: [[1, 2], [4, 5]]
array5: [[1, 2, 3], [4, 5, 6]]


In [77]:
# 불린 인덱싱 : 조건 필터링과 검색을 할 수 있는 인덱스 방식
print(array1d)

array3 = array1d[array1d>5]
print("array1d>5 불린 인덱싱 결과값", array3)

boolean_indexes = np.array([True, True, False, False, False,  True,  True,  True,  True])
array4 = array1d[boolean_indexes]
print(array4)

[1 2 3 4 5 6 7 8 9]
array1d>5 불린 인덱싱 결과값 [6 7 8 9]
[1 2 6 7 8 9]


## 6. 행렬의 정렬 : sort(), argsort()
- np.sort(): 원본 변경 X
- ndarray.sort(): 원본 변경 
- argsort() : 인덱스 반환

In [81]:
org_array = np.array([3,1,5,9])

#1. np.sort()
sort_array1 = np.sort(org_array)
print("sort_array1:", sort_array1)
print("호출 후 원본 행렬:", org_array)

#2. ndarray.sort()
sort_array2 = org_array.sort()
print("sort_array2:", sort_array2)
print("호출 후 원본 행렬:", org_array)

sort_array1: [1 3 5 9]
호출 후 원본 행렬: [3 1 5 9]
sort_array2: None
호출 후 원본 행렬: [1 3 5 9]


In [83]:
# 내림차순 정렬 : [::-1]
np.sort(org_array)[::-1]

array([9, 5, 3, 1])

In [84]:
# 2차원 행렬 정렬하기 
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print("row 방향으로 정렬:\n", sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print("column 방향으로 정렬:\n", sort_array2d_axis1)

row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [87]:
# 정렬된 행렬의 인덱스 반환하기 : np.argsort()
org_array = np.array([2,6,3,1])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print("행렬 정렬 시 원본 행렬의 인덱스:", sort_indices)

sort_indices = np.argsort(org_array)[::-1]
print("행렬 내림차순 정렬 시 원본 행렬의 인덱스:", sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [3 0 2 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [1 2 0 3]


넘파이의 ndarray는 RDBMS의 Table이나 pandas의 dataframe과 같은 메타 데이터를 가질 수 없다. 따라서 실제 값과 그 값과 매칭되는 메타 데이터를 별도의 ndarray로 가져야 한다. 
아래의 코드에서 예시를 들어보겠다. 

In [90]:
name_array = np.array(['지수','제니','리사','로제'])
score_array = np.array([56,98,76,64])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적이 낮은 순으로 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 3 2 1]
성적이 낮은 순으로 이름 출력: ['지수' '로제' '리사' '제니']


## 7. 선형대수 연산: 행렬 내적과 전치 행렬 구하기

In [94]:
# 행렬 내적
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[7,8],
              [9,10],
              [11,12]])

dot_product = np.dot(A,B)
print("행렬 내적:\n" ,dot_product)

행렬 내적:
 [[ 58  64]
 [139 154]]


In [95]:
# 전치 행렬 
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print("전치 행렬\n", transpose_mat)

전치 행렬
 [[1 3]
 [2 4]]
